<?php

use Illuminate\Database\Seeder;
use App\Employee;
use Carbon\Carbon;

class EmployeeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00487',
            'title' => '',
            'f_name' => 'สมยศ',
            'l_name' => 'อรุณมาศ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00488',
            'title' => '',
            'f_name' => 'โสภิดา',
            'l_name' => 'สัตตบุศย์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00491',
            'title' => '',
            'f_name' => 'สิริเพ็ญ',
            'l_name' => 'ยศไกร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00493',
            'title' => '',
            'f_name' => 'เดชะ',
            'l_name' => 'สุวรรณสาร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00496',
            'title' => '',
            'f_name' => 'เผด็จ',
            'l_name' => 'จุลถาวร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00497',
            'title' => '',
            'f_name' => 'พิสัน',
            'l_name' => 'เผื่อนน้อย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00499',
            'title' => '',
            'f_name' => 'ดวงรัตน์',
            'l_name' => 'ชุณหขจร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00500',
            'title' => '',
            'f_name' => 'อภิวรรณ',
            'l_name' => 'เจริญเกตุ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00501',
            'title' => '',
            'f_name' => 'วิโรจน์ ',
            'l_name' => 'ธนวิวัฒน์สกุล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00505',
            'title' => '',
            'f_name' => 'สรรเพชร',
            'l_name' => 'สารพัฒน์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00507',
            'title' => '',
            'f_name' => 'สุดารัตน์',
            'l_name' => 'ขันเงิน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00508',
            'title' => '',
            'f_name' => 'สิทธิธรรม',
            'l_name' => ' สิงหลกะ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00509',
            'title' => '',
            'f_name' => 'จารุกิติ์',
            'l_name' => 'บุตรฉ่ำ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00511',
            'title' => '',
            'f_name' => 'สมชาย',
            'l_name' => 'แก้วละม้าย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00513',
            'title' => '',
            'f_name' => 'ผดุงเดช',
            'l_name' => 'ขำบริสุทธิ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00515',
            'title' => '',
            'f_name' => 'เฉลิมฤดี',
            'l_name' => 'ช่วยชูกูล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00516',
            'title' => '',
            'f_name' => 'วริศ',
            'l_name' => 'กระจับเผือก',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00522',
            'title' => '',
            'f_name' => 'วันนี',
            'l_name' => 'อับดุลฮาดี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00525',
            'title' => '',
            'f_name' => 'ชินพล',
            'l_name' => 'โสณมัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00526',
            'title' => '',
            'f_name' => 'นิภัทร์',
            'l_name' => 'ประเสริฐศิลป์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00527',
            'title' => '',
            'f_name' => 'จิรภัทร์',
            'l_name' => 'ฟักฟูม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00528',
            'title' => '',
            'f_name' => 'นิวัฒน์',
            'l_name' => 'เจริญราษฎร์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00530',
            'title' => '',
            'f_name' => 'สุมาลา',
            'l_name' => 'สุทธิประภา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00531',
            'title' => '',
            'f_name' => 'พนา',
            'l_name' => 'นาคเจียม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00533',
            'title' => '',
            'f_name' => 'สมจิตร',
            'l_name' => 'พานมะลิ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00535',
            'title' => '',
            'f_name' => 'นวน',
            'l_name' => 'เกิดปั้น',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00541',
            'title' => '',
            'f_name' => 'อำพันธ์',
            'l_name' => 'พวงพลอย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00544',
            'title' => '',
            'f_name' => 'สาม',
            'l_name' => 'ยำเกรง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00545',
            'title' => '',
            'f_name' => 'เอกราช ',
            'l_name' => 'ป้อมสุวรรณ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00547',
            'title' => '',
            'f_name' => 'ธงชัย ',
            'l_name' => 'คล้ายสุวรรณ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00548',
            'title' => '',
            'f_name' => 'พิชิต',
            'l_name' => 'รอดแก้ว',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00557',
            'title' => '',
            'f_name' => 'ประกิต ',
            'l_name' => 'ชัยปรีชา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00559',
            'title' => '',
            'f_name' => 'อุทิศ ',
            'l_name' => 'วีระพัฒน์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00561',
            'title' => '',
            'f_name' => 'นพดล ',
            'l_name' => 'เสนะแสง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00563',
            'title' => '',
            'f_name' => 'ประหยัด',
            'l_name' => 'วงศ์เกรียงไกร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00565',
            'title' => '',
            'f_name' => 'ณรงค์ฤทธิ์',
            'l_name' => 'คัมภิรานนท์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00566',
            'title' => '',
            'f_name' => 'บุญรอด ',
            'l_name' => 'ฟุ้งเฟื่อง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00568',
            'title' => '',
            'f_name' => 'จิรศักดิ์',
            'l_name' => 'มูเก็ม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00569',
            'title' => '',
            'f_name' => 'คมสัน ',
            'l_name' => 'นิ่มมงคลศิลป์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00570',
            'title' => '',
            'f_name' => 'ณัฎฐพล',
            'l_name' => 'ขาวประเสริฐ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00572',
            'title' => '',
            'f_name' => 'วรพล ',
            'l_name' => 'ล้อมวงษ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00573',
            'title' => '',
            'f_name' => 'ธวัชชัย',
            'l_name' => 'เดชวิลัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00574',
            'title' => '',
            'f_name' => 'สุระศักดิ์',
            'l_name' => 'สุภาพ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00576',
            'title' => '',
            'f_name' => 'จาหิรัญ',
            'l_name' => 'ฟื่องฟุ้ง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00578',
            'title' => '',
            'f_name' => 'ณรงค์ฤทธิ์',
            'l_name' => 'เกาะเพชร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00579',
            'title' => '',
            'f_name' => ' นันธสรณ์',
            'l_name' => 'เลิศผลบุญ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00580',
            'title' => '',
            'f_name' => 'วิเชียร',
            'l_name' => 'หงษ์โม้',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00581',
            'title' => '',
            'f_name' => 'ไพรัช ',
            'l_name' => 'สวัสดีผล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00582',
            'title' => '',
            'f_name' => 'บุญช่วย ',
            'l_name' => 'สุขเขียว',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00585',
            'title' => '',
            'f_name' => 'จรินทร์',
            'l_name' => 'สวัสดีผล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00588',
            'title' => '',
            'f_name' => 'วิทยา',
            'l_name' => 'สายน้ำเงิน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00589',
            'title' => '',
            'f_name' => 'สามารถ',
            'l_name' => 'มหรรณพ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00590',
            'title' => '',
            'f_name' => 'นิรันดร',
            'l_name' => 'บู่น้อย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00591',
            'title' => '',
            'f_name' => 'สามารถ ',
            'l_name' => 'ศิริพรรณ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00592',
            'title' => '',
            'f_name' => 'วชิราวิทย์',
            'l_name' => 'จรรยงพันธุ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00593',
            'title' => '',
            'f_name' => 'จิระพันธุ์',
            'l_name' => 'สุขสุเมฆ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00594',
            'title' => '',
            'f_name' => 'ศิริพงค์',
            'l_name' => 'จังอินทร์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00595',
            'title' => '',
            'f_name' => 'อาณัติ ',
            'l_name' => 'ศิริบาล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00596',
            'title' => '',
            'f_name' => 'นวพล',
            'l_name' => 'สัญฐิติพงศ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00597',
            'title' => '',
            'f_name' => 'สามารถ',
            'l_name' => ' จิ๋วสกุล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00600',
            'title' => '',
            'f_name' => 'สมบัติ',
            'l_name' => 'สิทธิโยธิน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00603',
            'title' => '',
            'f_name' => 'ธงชัย ',
            'l_name' => 'คล้ายสุวรรณ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00604',
            'title' => '',
            'f_name' => 'ชิณญชร',
            'l_name' => 'พัชรจรีกุล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00606',
            'title' => '',
            'f_name' => 'ชินชาต',
            'l_name' => 'มังคล้าย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00607',
            'title' => '',
            'f_name' => 'กฤติพงศ์',
            'l_name' => 'พองชัยภูมิ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00611',
            'title' => '',
            'f_name' => 'ชาลี',
            'l_name' => 'ติเพียร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00612',
            'title' => '',
            'f_name' => 'สมศักดิ์',
            'l_name' => 'มีล้ำ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00617',
            'title' => '',
            'f_name' => 'บุญเสริม',
            'l_name' => 'แพร่ศิริรักษ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00618',
            'title' => '',
            'f_name' => 'กิตติศักดิ์',
            'l_name' => 'บีซัน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00619',
            'title' => '',
            'f_name' => 'ปราโมทย์',
            'l_name' => 'สารรัตน์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00621',
            'title' => '',
            'f_name' => 'ทวัฒธ์',
            'l_name' => 'สงทิม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00624',
            'title' => '',
            'f_name' => 'สาธิต',
            'l_name' => 'จิระวงศ์วาน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00625',
            'title' => '',
            'f_name' => 'สมคิด',
            'l_name' => 'บุติพันคา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00626',
            'title' => '',
            'f_name' => 'พูลทรัพย์',
            'l_name' => 'วุฑฒิโกวิทย์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00627',
            'title' => '',
            'f_name' => 'นพพร',
            'l_name' => 'อยู่อยู่',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00632',
            'title' => '',
            'f_name' => ' วันชัย',
            'l_name' => 'เดชวิลัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00636',
            'title' => '',
            'f_name' => 'สุภาพ ',
            'l_name' => 'ประเทศสิงห์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00637',
            'title' => '',
            'f_name' => 'ปราโมทย์',
            'l_name' => 'จันทิสาร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00638',
            'title' => '',
            'f_name' => 'ประยุทธ',
            'l_name' => 'ชุดนอก',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '00876',
            'title' => '',
            'f_name' => 'ดวงศธร',
            'l_name' => 'มนต์ประเสริฐศรี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01108',
            'title' => '',
            'f_name' => 'ปริวัฒน์',
            'l_name' => 'เศรษฐบุตร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01162',
            'title' => '',
            'f_name' => 'นรุตม์ชัย',
            'l_name' => 'สวนหนองแวง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01182',
            'title' => '',
            'f_name' => 'ขวัญชัย',
            'l_name' => 'เตาศิลานนท์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01183',
            'title' => '',
            'f_name' => 'ศิริยส',
            'l_name' => 'ประสบวิทยา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01195',
            'title' => '',
            'f_name' => 'คำรณ',
            'l_name' => 'ประดับศิลป์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01197',
            'title' => '',
            'f_name' => 'พลกฤษณ์',
            'l_name' => 'ทองชำนาญ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01198',
            'title' => '',
            'f_name' => 'นราวุฒิ',
            'l_name' => 'บุญล้อม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01222',
            'title' => '',
            'f_name' => 'เกรียงไกร',
            'l_name' => 'พิมเสน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01223',
            'title' => '',
            'f_name' => 'พิษณุ',
            'l_name' => 'กระแสขันธ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01245',
            'title' => '',
            'f_name' => 'ปกาศิต ',
            'l_name' => 'ช่วยศรี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01250',
            'title' => '',
            'f_name' => 'เอกสิทธิ์ ',
            'l_name' => ' เซอรัมย์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01302',
            'title' => '',
            'f_name' => 'พรรณิภา',
            'l_name' => 'ฟุ้งเฟื่อง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01356',
            'title' => '',
            'f_name' => 'มนัสนันท์',
            'l_name' => 'นันทะสิงห์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01363',
            'title' => '',
            'f_name' => 'ธนิยา',
            'l_name' => 'มั่งสูงเนิน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01433',
            'title' => '',
            'f_name' => 'ชวภณ',
            'l_name' => 'ครองกิจการ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01491',
            'title' => '',
            'f_name' => 'วรรณรพี',
            'l_name' => 'ภูรีโภคิน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01525',
            'title' => '',
            'f_name' => 'พรพิมล',
            'l_name' => 'นฤภัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01569',
            'title' => '',
            'f_name' => 'พันนี',
            'l_name' => 'อาจวิชัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01594',
            'title' => '',
            'f_name' => 'ลำดวน',
            'l_name' => 'เหล่านอก',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01704',
            'title' => '',
            'f_name' => 'พรศิริ',
            'l_name' => 'อินตามา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01710',
            'title' => '',
            'f_name' => 'คมสัน',
            'l_name' => 'อุ่นใจ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01724',
            'title' => '',
            'f_name' => ' ธีรพงศ์',
            'l_name' => 'สกุลทองวัฒนา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01730',
            'title' => '',
            'f_name' => 'อภิวัฒน์',
            'l_name' => 'หนูด้วง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01741',
            'title' => '',
            'f_name' => 'ธวัลรัชน์',
            'l_name' => 'ปัญญานุมาภรณ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01749',
            'title' => '',
            'f_name' => 'ศักดิ์ชัย',
            'l_name' => 'แซ่กั๋ง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01751',
            'title' => '',
            'f_name' => 'สุทิน',
            'l_name' => 'จูกลิ่น',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01752',
            'title' => '',
            'f_name' => 'อนุสาท',
            'l_name' => 'สีลุน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01757',
            'title' => '',
            'f_name' => 'ประวิทย์ ',
            'l_name' => 'กีรอารีย์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01761',
            'title' => '',
            'f_name' => 'นาท ',
            'l_name' => 'ฝั้นเครือ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01762',
            'title' => '',
            'f_name' => 'อาณัติ ',
            'l_name' => 'ศิริบาล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01773',
            'title' => '',
            'f_name' => 'อนุศรา',
            'l_name' => 'เฮงสุวรรณ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01775',
            'title' => '',
            'f_name' => 'สุดารัตน์',
            'l_name' => 'ลืมอินทร์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01783',
            'title' => '',
            'f_name' => 'ธวัชชัย',
            'l_name' => 'เดชวิลัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01788',
            'title' => '',
            'f_name' => 'กนกโชติ',
            'l_name' => 'อรุณวรรณ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01794',
            'title' => '',
            'f_name' => 'ชญานิศา',
            'l_name' => 'รุ่งเรือง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01797',
            'title' => '',
            'f_name' => 'กนกรัชต์ ',
            'l_name' => 'ปัญญา',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01856',
            'title' => '',
            'f_name' => 'พรพิมล',
            'l_name' => 'นฤภัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01865',
            'title' => '',
            'f_name' => 'อนุชิต',
            'l_name' => 'มาไกล',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01871',
            'title' => '',
            'f_name' => 'วิษณุ',
            'l_name' => 'หอมเพชร',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01945',
            'title' => '',
            'f_name' => 'กรีฑา',
            'l_name' => 'ชากัณฑ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01946',
            'title' => '',
            'f_name' => 'เอกลักษณ์',
            'l_name' => 'ศรีสวัสดิ์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01947',
            'title' => '',
            'f_name' => 'มานิตย์',
            'l_name' => 'พิชัย',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01948',
            'title' => '',
            'f_name' => 'ธนากร',
            'l_name' => 'สุปราณี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01954',
            'title' => '',
            'f_name' => 'อรกานต์',
            'l_name' => 'ชูประจง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01955',
            'title' => '',
            'f_name' => 'อนุปัญโย',
            'l_name' => 'บัวน่วม',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01956',
            'title' => '',
            'f_name' => 'ประหยัด ',
            'l_name' => 'นาคเจือทอง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01965',
            'title' => '',
            'f_name' => 'กัลยรัตน์ ',
            'l_name' => 'แย้มสังข์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01977',
            'title' => '',
            'f_name' => 'สุธินันท์',
            'l_name' => 'เลื่อนศิริ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '01979',
            'title' => '',
            'f_name' => 'อัศวะเทพ',
            'l_name' => 'นาคงสี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02052',
            'title' => '',
            'f_name' => 'นิวัฒน์',
            'l_name' => 'เรืองศรี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02053',
            'title' => '',
            'f_name' => 'สุรชัย',
            'l_name' => 'เรืองศรี',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02054',
            'title' => '',
            'f_name' => 'วัฒนี ',
            'l_name' => 'สุนทรกิจเสนีย์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02085',
            'title' => '',
            'f_name' => 'สมควร',
            'l_name' => 'รอดปาน',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02106',
            'title' => '',
            'f_name' => 'ธนาพงษ์',
            'l_name' => 'พิมพ์ตะคลอง',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
        Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02117',
            'title' => '',
            'f_name' => 'วิราช',
            'l_name' => 'หอมประเสริฐ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '02126',
            'title' => '',
            'f_name' => 'ณรงค์ฤทธิ์',
            'l_name' => 'ศรีโรจน์',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);Employee::insert([
            'dep_id' => 7,
            'branch_id' => 1,
            'emp_code' => '10011',
            'title' => '',
            'f_name' => 'ธุรการ',
            'l_name' => 'ธุรการ',
            'nickname' => '',
            'remark' => '',
            'assign_flg' => 1,
            'trash' =>0,
            'created_at' => Carbon::now(),
        ]);
    }
}
