<?php

use Illuminate\Database\Seeder;
use App\Material;
use Carbon\Carbon;

class MaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    //ไฟฟ้า E01
        Material::insert([
            'name' => 'บัลลาสต์อิเล็กทรอนิกส์Philips 2 x 36W.',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 1,
            'm_no' => 'E01001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'บัลลาสต์อิเล็กทรอนิกส์Philips EB-C13+TL-D',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 1,
            'm_no' => 'E01002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'บัลลาสต์แกนเหล็กPHILIPS 18W.',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 1,
            'm_no' => 'E01003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E02
        Material::insert([
            'name' => 'สตาร์ทเตอร์ Philips 36W',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 2,
            'm_no' => 'E02001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สตาร์ทเตอร์ Philips S10 4-46W',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 2,
            'm_no' => 'E02002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ขั้วสตาร์ทเตอร์',
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 2,
            'm_no' => 'E02003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E03
        Material::insert([
            'name' => 'เซอร์กิตเบรคเกอร์20A.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 3,
            'm_no' => 'E03001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เซอร์กิตเบรคเกอร์16A.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 3,
            'm_no' => 'E03002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เซอร์กิตเบรคเกอร์32A.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 3,
            'm_no' => 'E03003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'SAFETY BREAKER 15A..', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 3,
            'm_no' => 'E03004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E04
        Material::insert([
            'name' => 'กระบอกฟิวส์กระปุก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 4,
            'm_no' => 'E04001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฟิวส์กระปุก500V. 50A.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 4,
            'm_no' => 'E04002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E05
        Material::insert([
            'name' => 'หม้อแปลงไฟPHILIPS 60W. 12V', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 5,
            'm_no' => 'E05001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E06
        Material::insert([
            'name' => 'หลอดไฟLED 8W. E27 Warm White', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips TLD 18W Cooldaylight', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips Tornado 20W Cooldaylight', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Osram Dulux T/E Plus 32W/840', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟHALOGEN Lamp 50w.230V.GU5.3', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟLED 5.5W.12VAC.GU5.3', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips Tornado 12W Cooldaylight', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips TLD 36W Cooldaylight', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips Tornado 24W Warm White', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ Philips Tornado 24W Cooldaylight', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS TL5 28W.Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06011',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS TL5 14W.Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06012',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS Capsule 50W.12V.sportlight GY6.35', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06013',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟLED5.5W.220V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06014',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 18W./865/2P Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06015',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 120W. E27 Flood light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06016',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 26W./865/2P Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06017',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 18W./865/4P Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06018',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟOSRAM 18W./865/G24d2 Coolday light', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06019',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ PHILIPS HALOGEN 75W.230V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06020',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ PHILIPS HALOGEN 50W.12V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06021',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟLUMAX LED 15W. E27 WarmWhite', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06022',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟสปอร์ตไลท์400W. E40', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06023',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS Halogen 75W.250V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06024',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟLONG PAR30 11W.230V.WarmWhite', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06025',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ6V.เขี้ยว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06026',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ18V. 0.1A.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06027',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS BN010C EcoFit LED tube lamp', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06028',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS Master 150W./640', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06029',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 400W./645 E40', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06030',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 160W. 230V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06031',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟLED WarmWhite 6W. 12V./AC MR16', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06032',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS LED WarmWhite 12V./AC MR16', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06033',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS LED CoolDay 12V./AC MR16', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06034',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟHALOGEN WarmWhite 230V./35W.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06035',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 25W. Classictone', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06036',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ 6V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06037',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS CoolDay 18W./865  4P', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06038',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 150W./R75 230V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06039',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟ150W./R75 230V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06040',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 11W./865  2P', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06041',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS WarmWhite LED spot PAR30S', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06042',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟP30 Dimmable WarmWhite 11W. 230V.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06043',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 5W.LED WarmWhite 12V/AC', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06044',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอดไฟPHILIPS 25W. T25', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06045',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หลอด+โคมไฟPHILIPS 50W.Halogen 12V. R11', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06046',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'โคมขาสปริงติดผนัง1x36w มีปีกอลูมิเนียม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 6,
            'm_no' => 'E06047',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E07
        Material::insert([
            'name' => 'เต้ารับคู่มีกราวด์ สีแดง PANASONIC', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เต้ารับคู่มีกราวด์ สีขาว PANASONIC', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'DIMMER SWITCH 300W.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'DIMMER SWITCH 500W.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สวิตซ์ทางเดียว PANASONIC รุ่น weg 5001k', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สวิตซ์ทางเดียว PANASONIC รุ่น weg 5002k', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สวิตซ์หรี่ไฟแบบหมุน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สวิตซ์แสง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'บล็อคลอยเบรคเกอร์', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'บล็อคลอย2x4', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หน้ากาก4ช่อง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07011',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝาพลาสติกกันน้ำ3ช่อง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07012',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝาหน้ากาก2ช่อง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07013',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝาหน้ากาก1ช่อง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07014',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝาหน้ากาก3ช่อง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 7,
            'm_no' => 'E07015',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 23,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E08
        Material::insert([
            'name' => 'สายไฟTHW 1 x 1 SQmm. สีขาว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายไฟTHW 1 x 1 SQmm. สีดำ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายไฟTHW 1 x 2.5 SQmm. สีแดง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายไฟTHW 1 x 2.5 SQmm. สีน้ำเงิน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายไฟTHW 1 x 2.5 SQmm. สีเทา', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายไฟTHW 1 x 2.5 SQmm. สีน้ำตาล', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 8,
            'm_no' => 'E08006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 11,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E09
        Material::insert([
            'name' => 'ปลั๊กผู้ยางดำ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 9,
            'm_no' => 'E09001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ปลั๊กผู้', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 9,
            'm_no' => 'E09002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E10
        Material::insert([
            'name' => 'ไส้ไก่พันสายไฟ 12 mm.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ไส้ไก่พันสายไฟสีดำ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ท่อหดดำ 7.5', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ท่อหดดำ 5.0', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ท่อหดดำ 1.0', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ท่อหดแดง 7.5', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เทปพันสายไฟ 3M Scotch 790', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เทปละลายสก๊อตซ์23', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เคเบิ้ลไทร์สีดำ 250 mm.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เคเบิ้ลไทร์สีดำ 15 mm.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เคเบิ้ลไทร์สีดำ 15 mm.', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 10,
            'm_no' => 'E10011',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E11
        Material::insert([
            'name' => 'ลูกเต๋าต่อสาย สีขาว ขนาด 15A', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วายนัท สีส้ม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วายนัท 3M/Z-CO-3M/R สีแดง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วายนัท 3M/Z-CO-3M/BL สีเทา', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วายนัท 3M/Z-CO-3M/Y สีเหลือง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'หางปลา', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 11,
            'm_no' => 'E11006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ไฟฟ้า E12
        Material::insert([
            'name' => 'OVERLOAD RELAY', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 12  ,
            'm_no' => 'E12001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'MAGNATIC CONTACTOR', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 12  ,
            'm_no' => 'E12002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);

    //ประปา W01
        Material::insert([
            'name' => 'ก๊อกเดี่ยวอ่างล้างหน้าแบบก้านโยก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกน้ำสนาม 3/4"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกสนามด้ามแดง SANWA 1/2"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกสนามด้ามแดง SANWA 3/4"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วาล์วเปิด-ปิดน้ำ 1ทางแบบก้านหมุน ST-354M', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกอ่างล้างหน้าทรงสูงสแตนเลส S-FLO', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกน้ำอ่างล้างมือ แบบคอยาวโค้ง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สต็อปวาล์ว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วาล์วน้ำSANWA 3/4 เกลียวใน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'วาล์วน้ำดี 1/2 x 1/2', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 13  ,
            'm_no' => 'W01010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ประปา W02
        Material::insert([
            'name' => 'สายชำระ+หัวชำระ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 14 ,
            'm_no' => 'W02001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายชำระ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 14 ,
            'm_no' => 'W02002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝักบัวมือ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 14 ,
            'm_no' => 'W02003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดหัวฉีดชะล้าง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 14 ,
            'm_no' => 'W02004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ประปา W03
        Material::insert([
            'name' => 'ชุดก้านโยกสุขภัณฑ์โถปัสสาวะ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ลูกยางเกลียวใหญ่ Hang', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ประเก็นยาง/O-RING 53021', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดลูกสูบฟลัชวาล์ว TOTO', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดก้านกระทุ้งฟลัชวาล์ว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดลูกสูบฟลัชวาล์ว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฟลัชวาล์วโถปัสสาวะแบบโยก GLOBO', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดลูกสูบฟลัชวาล์วปัสสาวะ', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดมือกดโถสุขภัณฑ์ COTTO', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดปุ่มกดชักโครก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดปุ่มกดโถปัสสาวะชาย', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03011',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ชุดน้ำทิ้ง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 15 ,
            'm_no' => 'W03012',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ประปา W04
        Material::insert([
            'name' => 'ชุดลูกลอยวาล์วฉาก3/4', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' => 16  ,
            'm_no' => 'W04001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ประปา W05
        Material::insert([
            'name' => 'ลด PVC 1" x 1/2"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ต่อตรง PVC 3/4', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ข้องอ PVC 3/4', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สามทาง PVC 3/4', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ปิด PVC 4"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ปิด PVC 1/2"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ต่อตรงเกลียวนอก 1/2 เหล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ต่อตรงเกลียวใน 1/2 ทองเหลือง', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ข้องอเกลียวใน 3/4 เหล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ต่อตรงเกลียวใน 3/4 เหล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05010',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เทปพันเกลียว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05011',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เข็มขัดรัดท่อ s211', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05012',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เข็มขัดรัดท่อ s219', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  17 ,
            'm_no' => 'W05013',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //ประปา W06
        Material::insert([
            'name' => 'ท่อยางน้ำร้อนตู้กดน้ำดื่ม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  18 ,
            'm_no' => 'W06001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกน้ำเย็นตู้น้ำดื่ม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  18 ,
            'm_no' => 'W06002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกน้ำร้อนตู้น้ำดื่ม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  18 ,
            'm_no' => 'W06003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ก๊อกน้ำร้อน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  18 ,
            'm_no' => 'W06004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);

    //โทรศัพท์ T01
        Material::insert([
            'name' => 'ปลั๊ก LAN Panasonic', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  19 ,
            'm_no' => 'T01001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'เต้ารับโทรศัพท์', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  19 ,
            'm_no' => 'T01002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //โทรศัพท์ T02
        Material::insert([
            'name' => 'สายโทรศัพท์ Phelps Dodge', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  20 ,
            'm_no' => 'T02001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายโทรศัพท์', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  20 ,
            'm_no' => 'T02002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สายแลน LAN', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  20 ,
            'm_no' => 'T02003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);

    //อาคาร B01
        Material::insert([
            'name' => 'โช้คอัพประตู VC752 Yale', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'โช้คประตูแบบฝังบน VVP รุ่นOC35', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'บานพับข้อศอกบานกระทุ้งVVP รุ่นFH-14', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ลูกล้อบานเลื่อน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'มือจับล็อคประตูกระจก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ผ้าม่าน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ตัวแขวนผ้าม่าน', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ยางอัดขอบมุ้งลวด', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  21 ,
            'm_no' => 'B01008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B02
        Material::insert([
            'name' => 'ชุดกุญแจลิ้นชักและตู้เก็บเอกสาร', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  22 ,
            'm_no' => 'B02001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'กุญแจโต๊ะ FRONT MOUNTED', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  22 ,
            'm_no' => 'B02002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ล้อเก้าอี้', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  22 ,
            'm_no' => 'B02003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ฝาปิดล็อคใบพัดลม', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  22 ,
            'm_no' => 'B02004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B03
        Material::insert([
            'name' => 'ใบตัดเครื่องตัดไฟเบอร์', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  23 ,
            'm_no' => 'B03001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B04
        Material::insert([
            'name' => 'ZINWELL HAE-45 FM-R65 CATV DISTRIBUTION AMPLIFIER', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'SPLITTER', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'POWER PASS IN1/OUT2', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'POWER PASS IN1/OUT6', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'PSI Only Channel Filter', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สปริตเตอร์3ทางพร้อมปลั๊ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สปริตเตอร์2ทางพร้อมปลั๊ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'แจ๊คทีวีผู้แบบเหล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'แจ๊คทีวีผู้ตัวงอแบบเหล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  24 ,
            'm_no' => 'B04009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B05
        Material::insert([
            'name' => 'น็อตเกลียวละเอียด ตัวผู้ 1 นิ้ว', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'น็อตเมียเกลียวละเอียด', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'สกรูเกลียวเล็ก', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'พุกพลาสติกดำ #M12', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05004',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'พุกพลาสติกขาว #M10', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05005',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'พุกพลาสติกขาว #M7', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05006',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'พุกเหล็ก 3/8', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05007',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ตะปูตอกสังกะสี 1 3/4 x 13', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05008',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'DRYWALL SCREWS', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  25 ,
            'm_no' => 'B05009',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B06
        Material::insert([
            'name' => 'แปรงทาสี 3"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  26 ,
            'm_no' => 'B06001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ลูกกลิ้งสี 4"', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  26 ,
            'm_no' => 'B06002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    //อาคาร B07
        Material::insert([
            'name' => 'ถ่าน 3 A', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  27 ,
            'm_no' => 'B07001',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ถ่าน 2 A', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  27 ,
            'm_no' => 'B07002',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
        Material::insert([
            'name' => 'ถ่าน 9 A', 
            'desc' => '',
            'branch_id' => 1,
            'm_t_id' =>  27 ,
            'm_no' => 'B07003',
            'max' => 100,
            'min' => 10,
            'status' => 1,
            'trash' => 0,
            'unit_id' => 10,
            'created_at' => Carbon::now(),
        ]);
    
    }
}
